#!/bin/bash

# INTENDED FOR: OSX, LINUX & MSYS
if [ -f ~/.profile_x ]; then
	source ~/.profile_x
	source ~/.aliases_cordova
	source ~/.aliases_npm
fi

# INTENDED FOR: OSX
if [ -f ~/.profile_osx ]; then
	source ~/.profile_osx
fi

# INTENDED FOR: Linux
if [ -f ~/.profile_linux ]; then
	source ~/.profile_linux
fi

# INTENDED FOR: MSYS
if [ -f ~/.profile_msys ]; then
	source ~/.profile_msys
fi
