#!/bin/bash

# INTENDED FOR: OSX & LINUX

# Prompt display
export PROMPTERTYPE=short
function prompter(){
	local _ps1="$ "
	if [ $# -gt 0 ]; then
		export PROMPTERTYPE="$1"
	fi

	case "$PROMPTERTYPE" in
	long)
		_ps1="\u @$(hostname -s) in \$PWD $ "
		;;
	short)
		_ps1="`pwd | sed "s#$HOME#~#"` $ "
		;;
	z)
		_ps1="`pwd | sed "s#$HOME#~#" | sed "s#\(/.\)\([^\/]*\)#\1#g"` $ "
		;;
	$)
		# just use _ps1="$ "
		;;
	esac

	PS1=$_ps1 ; export PS1
}
export PROMPT_COMMAND=prompter

# Sublime as editor, when possible
export EDITOR="subl"

# Easy navigation
alias cdd="cdl -"
alias ~="cdl ~"
alias ..="cdl .."
alias ...="cdl ../.."
alias ....="cdl ../../.."
alias .....="cdl ../../../.."

# Shortcuts
alias dl="cdl ~/Downloads"
alias dt="cdl ~/Desktop"
mkdir -p ~/Screenshots
alias sss="cdl ~/Screenshots"

# List all files colorized in long format
alias l="ls -l"

# List all files colorized in long format, including dot files
alias la="ls -la"

# List only directories
alias lsd='ls -l | grep "^d"'

# List only directories, including dot files
alias lsda='ls -la | grep "^d"'

# Remove directory
alias rd="rm -rf"

# Create a new directory and enter it
function md() {
	mkdir -p "$@" && cd "$@"
}

# Change directory and list contents
function cdl() {
	cd "$@" && la
}

# Lazy change directory and list contents
function cdz() {
	local ds=$(find "$@"* -maxdepth 0 -type d | wc -l)
	if [[ $ds -eq 1 ]]; then
		cdl $(find "$@"* -maxdepth 0 -type d)
	else
		printf "\nTOO LAZY\n========\n"
		find "$@"* -maxdepth 0 -type d
		printf "\n"
	fi
}

# Determine size of a file or total size of a directory
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh
	else
		local arg=-sh
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@"
	else
		du $arg .[^.]* *
	fi
}

# Open Editor
function e(){
	if [ "$1" = "" ]; then
		exec $EDITOR . &
	else
		exec $EDITOR "$1" &
	fi
}

# Open .profiles in Editor
function profiles(){
	e ~/.profiles
}
