#!/bin/bash

# INTENDED FOR: MSYS (WINDOWS)

# login SSH for git
# https://confluence.atlassian.com/display/BITBUCKET/Set+up+SSH+for+Git
SSH_ENV=$HOME/.ssh/environment
# start the ssh-agent
function start_agent {
	echo "Initializing new SSH agent..."
	# spawn ssh-agent
	/usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
	echo succeeded
	chmod 600 "${SSH_ENV}"
	. "${SSH_ENV}" > /dev/null
	/usr/bin/ssh-add
}
if [ -f "${SSH_ENV}" ]; then
	. "${SSH_ENV}" > /dev/null
	ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
		start_agent;
}
else
	start_agent;
fi

# Open explorer
alias open="explorer"

# Sublime as editor, when possible
export EDITOR="/c/Program\ Files/Sublime\ Text\ 2/sublime_text.exe"

# Sublime Text 2
alias subl="/c/Program\ Files/Sublime\ Text\ 2/sublime_text.exe"

# Open Chrome from terminal
alias chrome="start chrome"

# Open explorer to system Fonts
alias fonts="explorer /c/Windows/Fonts"

# Clear terminal screen
alias cl="clear"
