#!/bin/bash

# UBU _profile

export LS_COLORS="di=32;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"

# Default to long prompter, because I'm likely to be on a server
prompter long

# misc
alias ls="ls --color"
alias ack="ack-grep"

# Clipboard copy/paste like a Mac
alias pbcopy="xargs -0 -I {} echo \"{}\" > /tmp/clipboard"
alias pbpaste="cat /tmp/clipboard"

if [[ $- == *i* ]]; then
  # is an interactive shell
  # Cache my ssh password :P
  eval "$(ssh-agent)" > /dev/null
  ssh-add /home/$USER/.ssh/id_rsa
fi
