#!/bin/bash

# Cordova PhoneGap aliases (v3.X)
alias cor="cordova" # candidate for "corc"
alias cori="cordova info"
alias corc="cordova create"

# Platform specifics for Cordova PhoneGap
alias corpfl="cordova platform ls"
alias corpfa="cordova platform add"
alias corpfr="cordova platform remove"
alias corpfx="corpfr"

# Build specifics for Cordova PhoneGap
alias corpre="cordova prepare"
alias corco="cordova compile"
alias corb="cordova build"

# Running specifics for Cordova PhoneGap
alias corem="killall Simulator || echo && cordova emulate"
alias coremipse="corem --target=iPhone-SE"
alias coremip4="corem --target=iPhone-4s"
alias coremip5="corem --target=iPhone-5s"
alias coremip6="corem --target=iPhone-6s"
alias coremip6p="corem --target=iPhone-6s-Plus"
alias coremipad="corem --target=iPad-2"
alias coremip7="corem --target=iPhone-7"
alias coremip7p="corem --target=iPhone-7-Plus"
alias coremipadp="corem --target=iPad-Pro"
alias corr="cordova run"
alias cors="cordova serve"
alias corbs="cordova build && cordova serve"
alias corbem="killall Simulator || echo && cordova build && cordova emulate"
alias corbemip4="corbem --target=iPhone-4s"
alias corbemip5="corbem --target=iPhone-5s"
alias corbemip6="corbem --target=iPhone-6s"
alias corbemip6p="corbem --target=iPhone-6s-Plus"
alias corbemipad="corbem --target=iPad-2"
alias corbemipadp="corbem --target=iPad-Pro"

# Running iOS Simulator with Safari Web Inspector (for Debugging)
alias corbemd="corbem && ios-sim-inspector"

# Plugin specifics for Cordova PhoneGap
alias corp="cordova plugin" # candidate for "corpa"
alias corps="cordova plugin search"
alias corpl="cordova plugin ls"
alias corpa="cordova plugin add"
alias corpr="cordova plugin remove"
alias corpx="corpr"

# Common official plugins
alias corpa-battery-status="cordova plugin add cordova-plugin-battery-status"
alias corpa-camera="cordova plugin add cordova-plugin-camera"
alias corpa-console="cordova plugin add cordova-plugin-console"
alias corpa-contacts="cordova plugin add cordova-plugin-contacts"
alias corpa-device="cordova plugin add cordova-plugin-device"
alias corpa-device-motion="cordova plugin add cordova-plugin-device-motion"
alias corpa-device-orientation="cordova plugin add cordova-plugin-device-orientation"
alias corpa-dialogs="cordova plugin add cordova-plugin-dialogs"
alias corpa-file="cordova plugin add cordova-plugin-xxx"
alias corpa-file-transfer="cordova plugin add cordova-plugin-file-transfer"
alias corpa-geolocation="cordova plugin add cordova-plugin-geolocation"
alias corpa-globalization="cordova plugin add cordova-plugin-globalization"
alias corpa-inappbrowser="cordova plugin add cordova-plugin-inappbrowser"
alias corpa-media="cordova plugin add cordova-plugin-media"
alias corpa-media-capture="cordova plugin add cordova-plugin-media-capture"
alias corpa-network-information="cordova plugin add cordova-plugin-network-information"
alias corpa-splashscreen="cordova plugin add cordova-plugin-splashscreen"
alias corpa-statusbar="cordova plugin add cordova-plugin-statusbar"
alias corpa-vibration="cordova plugin add cordova-plugin-vibration"

# Common 3rd party plugins
alias corpa-3dtouch="cordova plugin add cordova-plugin-3dtouch"
alias corpa-background="cordova plugin add cordova-plugin-background-mode"
alias corpa-badge="cordova plugin add cordova-plugin-badge"
alias corpa-ga="cordova plugin add cordova-plugin-google-analytics"
alias corpa-keyboard="cordova plugin add cordova-plugin-keyboard"
alias corpa-push="cordova plugin add https://github.com/phonegap-build/PushPlugin.git"
alias corpa-socialsharing="cordova plugin add cordova-plugin-x-socialsharing"
alias corpa-spinnerdialog="cordova plugin add https://github.com/Paldom/SpinnerDialog.git"
alias corpa-toast="cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git"
alias corpa-3dtouch="cordova plugin add cordova-plugin-webviewcolor"
alias corpa-purchase="cordova plugin add cordova-plugin-inapppurchase"

# Cordova Resource Generators
# https://github.com/busterc/cordova-resource-generators
alias cgicons="cordova-generate-icons"
alias cgscreens="cordova-generate-splash-screens"

# Create an empty Cordova Project
function corce() {
  cordova create "$@"

  if [[ $? -eq 0 ]]; then
    cd "$1"
    rm -rf www/*
  fi
}

# Create a Cordova Project using Yo Generator: cordova-www
function corc-www() {
  cordova create "$@"

  if [[ $? -eq 0 ]]; then
    cd "$1"
    rm -rf www/*
    yo cordova-www

    microgen $MICROGEN_TEMP_DIR/cordova-common/package.json.hbs
  fi
}
