#!/usr/bin/env bash

# Init
alias gt_init_add_commit_v0="git init && git add . && git commit -m 0.0.0"

# Add
alias gt_add="git add"
alias gt_add_patch="git add -p"

# Branch
alias gt_branch_list="git branch --list"
alias gt_branch_list_delete_interactive='git branch | grep -v "^\*" | sed "s/^[ \t]*//" | ipt -m | xargs -r git branch -D'
alias gt_checkout_new_branch="git checkout -b"

## Diff
alias gt_difftool="git difftool"
alias gt_difftool_master_origin_master="git fetch origin && git difftool origin/master master"
alias gt_difftool_master_origin_master_filenames_only="git fetch origin && git difftool --name-only origin/master master"
alias gt_difftool_master_upstream_master="git fetch upstream && git difftool master upstream/master"
alias gt_difftool_master_upstream_master_filenames_only="git fetch upstream && git difftool --name-only master upstream/master"

## Log
alias gt_log="git log --graph --oneline --decorate --all"
alias gt_log_past_7_days="git log --since='7 days ago' --graph --oneline --decorate --all"
alias gt_log_past_30_days="git log --since='30 days ago' --graph --oneline --decorate --all"

## Remote
alias gt_view_remotes="git remote -v"

## Status
alias gt_view_status="git status"

# Clean up
alias gt_clean_ignored_files="git clean -Xdf"
alias gt_clean_ignored_files_dryrun="git clean -Xdfn"

# GitHub Public API Rate Limit
alias github_check_rate_limit="curl -s https://api.github.com/rate_limit | less"

function gt_tag_easy_same_annotation_and_message() {
  if [[ $# -eq 0 ]]; then
    cat <<EOF

  Usage: gt_tag_easy_same_annotation_and_message <tagname>

  Creates an annotated git tag with the same annotation and message.

  For example:
    gt_tag_easy_same_annotation_and_message v1.2.3
    > tag: "v1.2.3" message: "v1.2.3"

EOF
  else
    git tag -a "$@" -m "$@"
  fi
}

function gt_tag_easy_version_annotation() {
  if [[ $# -eq 0 ]]; then
    cat <<EOF

  Usage: gt_tag_easy_version_annotation <version>

  Creates an annotated git tag with a "v" prefix
  and the version as the annotation and message.

  For example:
    gt_tag_easy_version_annotation 1.2.3
    > tag: "v1.2.3" message: "1.2.3"

EOF
  else
    git tag -a "v$@" -m "$@"
  fi
}

function gt_tag_with_date_time() {
  gt_tag_easy_same_annotation_and_message "$(date +"%Y.%m.%d-%H%M%S")"
}

function gt_difftool_all_subdirectories_with_orign_master() {
  for d in $(find . -name ".git" -maxdepth 2); do
  hr
  (
    cd "$d"/..
    echo "processing $d" | sed 's#\/\.git##';
    git fetch origin && git difftool master origin/master
  )
  done
}

function gt_difftool_all_subdirectories_with_upstream_master() {
  for d in $(find . -name ".git" -maxdepth 2); do
  hr
  (
    cd "$d"/..
    echo "processing $d" | sed 's#\/\.git##';
    git fetch upstream && git difftool master upstream/master
  )
  done
}

function gt_clean_all_subdirectories_ignored_files() {
  for d in $(find . -name ".git" -maxdepth 2); do
  hr
  (
    cd "$d"/..
    echo "processing $d" | sed 's#\/\.git##';
    git clean -Xdf
  )
  done
}

function gt_clean_all_subdirectories_ignored_files_dryrun() {
  for d in $(find . -name ".git" -maxdepth 2); do
  hr
  (
    cd "$d"/..
    echo "processing $d" | sed 's#\/\.git##';
    git clean -Xdfn
  )
  done
}

function gt_view_status_all_subdirectories() {
  for d in $(find . -name ".git" -maxdepth 2); do
  hr
  (
    cd "$d"/..
    echo "processing $d" | sed 's#\/\.git##';
    git status
  )
  done
}

function gt_pull_all_subdirectories() {
  for d in $(find . -name ".git" -maxdepth 2); do
  hr
  (
    cd "$d"/..
    echo "processing $d" | sed 's#\/\.git##';
    git pull
  )
  done
}

function degit_repo() {
  if [[ $# -ne 2 ]]; then
    cat <<EOF

  Get a git repo for a new project and remove its git history.

  Usage: degit_repo <repo> <dest>

EOF
  else
    git clone --depth 1 "$1" "$2" &&
    cd "$2" &&
    rm -rf .git
  fi
}

function degit_github_repo() {
  if [[ $# -ne 2 ]]; then
    cat <<EOF

  Get a git repo from GitHub for a new project and remove its git history.

  Usage: degit_github_repo <repo> <dest>

EOF
  else
    git clone --depth 1 "git@github.com:$1" "$2" &&
    cd "$2" &&
    rm -rf .git
  fi
}

function degit_bitbucket_repo() {
  if [[ $# -ne 2 ]]; then
    cat <<EOF

  Get a git repo from BitBucket for a new project and remove its git history.

  Usage: degit_bitbucket_repo <repo> <dest>

EOF
  else
    regit "git@bitbucket.org:$1" "$2"
  fi
}

function degit_dist_from_repo() {
  if [[ $# -ne 2 ]]; then
    cat <<EOF

  Get dist/**/* from a git repo

  Usage: degit_dist_from_repo <repo> <dest>

EOF
  else
    temp_dir="$(mktemp -d)"
    git clone --depth 1 "$1" "$temp_dir" &&
    cp -r "$temp_dir/dist/" "$2" &&
    rm -rf "$temp_dir"
  fi
}

function gt_stash_export() {
  (
    IFS=$'\n'
    stash_dir="${PWD}/stashes"
    mkdir -p "$stash_dir"
    cd "$stash_dir"
    stashes=( $(git stash list) )

    for stash in "${stashes[@]}"; do
      id=$( echo "$stash" | cut -d: -f1 )
      label=$( echo "$stash" | cut -d: -f3 )

      diffs=$(git --no-pager stash show --no-color -p "$id")
      diff_file="${stash_dir}/$stash.diff"
      [[ $diffs ]] && echo "$diffs" > "$diff_file" && echo "=> $diff_file"

      untracked=$(git --no-pager show --no-color "$id"^3 2>/dev/null)
      untracked_file="${stash_dir}/$stash.untracked"
      [[ $untracked ]] && echo "$untracked" > "$untracked_file" && echo "=> $untracked_file"
    done
  )
}
