#!/usr/bin/env bash

# CLI for JS `encodeURIComponent` handy for quick svg conversions
function encode_uri() {
  if [[ $# -eq 0 ]]; then
    cat <<'EOF'

  Usage: encode_uri <string>

  Example: $ encode_uri "$(cat logo.svg)" | pbcopy

EOF
  else
    local fn
    if echo "$1" | grep "\"" >/dev/null && echo "$1" | grep "'" > /dev/null; then
      echo "Error: string contains both single and double quotes."
      return 1
    elif echo "$1" | grep "\'" >/dev/null; then
      fn="encodeURIComponent(\"$1\")"
    else
      fn="encodeURIComponent('$1')"
    fi
    node -p "$fn"
  fi
}

# CLI for JS `decodeURIComponent` handy for quick svg conversions
function decode_uri() {
  if [[ $# -eq 0 ]]; then
    cat <<'EOF'

  Usage: decode_uri <string>

  Example: $ decode_uri "%3Csvg%3E%3C%2Fsvg%3E" | pbcopy"

EOF
  else
    local fn
    if echo "$1" | grep "\"" >/dev/null && echo "$1" | grep "'" > /dev/null; then
      echo "Error: string contains both single and double quotes."
      return 1
    elif echo "$1" | grep "\'" >/dev/null; then
      fn="decodeURIComponent(\"$1\")"
    else
      fn="decodeURIComponent('$1')"
    fi
    node -p "$fn"
  fi
}


# Defaults for `iconr` and fix classname preprending
if command -v iconr >/dev/null 2>&1; then
  alias iconz="iconr . . -avNnokSd -c=i.icon.icon- | sed 's#\.i\.icon\.#i\.icon\.#g' > _iconz.css"
fi

# Add color to svgs
function fill_svg() {
  if [[ $# -lt 3 ]] || [[ $1 == *".svg" ]] || [[ $2 == *".svg" ]]; then
    cat <<'EOF'

    Usage: fill_svg <color-name> <color> <svg-file>...

    Description: adds `fill="color"` to svg `<path>` element and saves
    the new file(s) in ./filled/<color-name>/*

    Options:

      <color-name>  a user friendly name that gets applied to each filename
      <color>       the actual color to apply; rgb(), hex or html color-name
      <svg-file>    the source files

    Examples:

      $ fill_svg burnt-orange "#bf5700" *.svg

      $ fill_svg orange orange *.svg

EOF
  else
    local colorname="$1"
    shift
    local color="$1"
    shift

    local dest="./filled/$colorname"
    mkdir -p "$dest"

    for file in $@; do
      outfile="$(echo $file | sed s#\.svg#\-$colorname\.svg#)"
      cat $file | sed 's/\<path/\<path fill="'$color'"/' > "$dest/$outfile"
      echo "$dest/$outfile"
    done
  fi
}

# FontAwesome to SVG (font glyphs to individual svg files)
function fontawesome_to_svg() {
  git clone https://github.com/fortawesome/font-awesome
  mkdir -p ./fontawesome-svg/
  svg-caster --svg-font ./font-awesome/fonts/fontawesome-webfont.svg --svg-font-css ./font-awesome/css/font-awesome.css --out-svg ./fontawesome-svg/
  rm -rf ./font-awesome/
}

# ImageMagick FavIcon Generator
function favicon_generator_via_imagemagick() {
  if [[ $# -eq 0 ]]; then
    printf "\n  Usage: favicon_generator_via_imagemagick <image-filename>\n\n"
  else
    convert "$1" -bordercolor white -border 0 \
      \( -clone 0 -resize 16x16 \) \
      \( -clone 0 -resize 32x32 \) \
      \( -clone 0 -resize 48x48 \) \
      \( -clone 0 -resize 64x64 \) \
      -delete 0 -alpha off -colors 256 favicon.ico
  fi
}

# Move images into YYYY-MM-DD directories
move_images_to_YYYY-MM-DD_subdirectories() {
  if [ $# -eq 0 ]; then
    cat <<EOF

  Usage: move_images_to_YYYY-MM-DD_subdirectories <file>

EOF
    return 1
  fi

  for file in "$@"; do
    echo "$file"
    dir=$(stat -f "%Sm" -t "%Y-%m-%d" "$file")
    mkdir -p "$dir"
    mv "$file" "$dir"
  done
}
