#!/usr/bin/env bash

# Aliases for NGINX Helper
alias nginx_list_available_websites="nginx_helper -la"
alias nginx_list_enabled_websites="nginx_helper -le"
alias nginx_enable_website="nginx_helper -es"
alias nginx_disable_website="nginx_helper -ds"
alias nginx_cd_to_sites_available="nginx_helper -ca"
alias nginx_cd_to_sites_enabled="nginx_helper -ce"

# NGINX Helper
function nginx_helper() {
  function usage() {
    cat <<EOF

  Usage: nginx_helper <options>

    Description: NGINX utils

    Options:

      -la            list available websites
      -le            list enabled websites
      -es <website>  enable a website
      -ds <website>  disable a website
      -ca            cd to /etc/nginx/sites-available
      -ce            cd to /etc/nginx/sites-enabled

EOF
  }

  if [[ $# -eq 0 ]]; then
    usage
  else

    local availableDir="/etc/nginx/sites-available/"
    local enabledDir="/etc/nginx/sites-enabled/"

    case "$1" in
    -la)
      ls $availableDir
      ;;
    -le)
      ls $enabledDir
      ;;
    -es)
      if [[ -f "$availableDir$2" ]]; then
        sudo ln -sfn "$availableDir$2" "$enabledDir$2"
        sudo nginx -s reload
      else
        printf "\n  Error: $2 was not found\n\n"
      fi
      ;;
    -ds)
      if [[ -f "$enabledDir$2" ]]; then
        sudo rm "$enabledDir$2"
        sudo nginx -s reload
      else
        printf "\n  Error: $2 was not found\n\n"
      fi
      ;;
    -ca)
      cd $availableDir
      ;;
    -ce)
      cd $enabledDir
      ;;
    *)
      usage
      ;;
    esac
  fi
}
