#!/bin/bash

## general info
#######################################

alias npmv="npm --version"
alias npml="npm list --depth 0"
alias npmlg="npm list --global --depth 0"
alias npmgl="npmlg"
alias npmo="npm outdated"
alias npmog="npmo --global"

## normal user local
#######################################

# local install
alias npmi="npm install"
alias npmis="npmi --save"
alias npmise="npmis --save-exact"
alias npmisd="npmi --save-dev"
alias npmisde="npmisd --save-exact"
alias npmiso="npmi --save-optional"
alias npmisoe="npmiso --save-exact"

# local update
alias npmup="npm update"

# local remove
alias npmr="npm remove"
alias npmrs="npmr --save"
alias npmrsd="npmr --save-dev"
alias npmrso="npmr --save-optional"
alias npmx="npmr"
alias npmxrs="npmrs"
alias npmxsd="npmrsd"
alias npmxso="npmrso"
alias npmxse="npmrse"

# misc
alias npmbump="npm version patch"

## super user local
#######################################

# local install
alias snpmi="sudo npm install"

# local update
alias snpmup="sudo npm update"

# local remove
alias snpmr="sudo npm remove"
alias snpmx="snpmr"

## super user global
#######################################

# global install
alias npmig="npm install --global"
alias npmgi="npmig"
alias npmg="npmig"
alias snpmig="sudo npm install --global"
alias snpmgi="snpmig"
alias snpmg="snpmig"

# global update
alias npmupg="npm update --global"
alias npmgup="npmupg"
alias snpmupg="sudo npm update --global"
alias snpmgup="snpmupg"

# global remove
alias npmrg="npm remove --global"
alias npmgr="npmrg"
alias npmxg="npmrg"
alias npmgx="npmrg"
alias snpmrg="sudo npm remove --global"
alias snpmgr="snpmrg"
alias snpmxg="snpmrg"
alias snpmgx="snpmrg"

# Run NPM Install on all subdirectories
function subnpmi() {
  for d in $(find . -name 'package.json' | grep -v 'node_modules' | sed 's/\/package\.json//g'); do
    hr
    (
      cd "$d"
      echo "NPM Installing $d";
      npm install
    )
  done
}

# Reinstall modules completely
## local, no save
function npmri() {
  npmrs "$@"
  npmi "$@"
}
## local, save
function npmris() {
  npmrs "$@"
  npmris "$@"
}
## local, save exact
function npmrise() {
  npmrs "$@"
  npmise "$@"
}
## local, save dev
function npmrisd() {
  npmrsd "$@"
  npmisd "$@"
}
## local, save dev exact
function npmrisde() {
  npmrsd "$@"
  npmisde "$@"
}
