#!/usr/bin/env bash

## general info
#######################################

alias npmv="npm --version"
alias npml="npm list --depth 0 | less"
alias npmlg="npm list --global --depth 0 | less"
alias npmgl="npmlg"
alias npmo="npm outdated"
alias npmog="npmo --global"

## normal user local
#######################################

# local install
alias npmi="npm install"
alias npmise="npmi --save-exact"
alias npmisd="npmi --save-dev"
alias npmisde="npmisd --save-exact"
alias npmiso="npmi --save-optional"
alias npmisoe="npmiso --save-exact"

# local update
alias npmup="npm update"

# local remove
alias npmr="npm remove"
alias npmrs="npmr --save"
alias npmrsd="npmr --save-dev"
alias npmrso="npmr --save-optional"
alias npmx="npmr"
alias npmxrs="npmrs"
alias npmxsd="npmrsd"
alias npmxso="npmrso"
alias npmxse="npmrse"

# misc
alias npmbump="npm version patch"
alias npmy="npm init -y"
alias ppj="npx prettier-package-json --write ./package.json"
alias npmc="npm-check -u"
alias npmcg="npm-check -gu"
alias npmt="npm test"
alias npmit="npm it"

## super user local
#######################################

# local install
alias snpmi="sudo npm install"

# local update
alias snpmup="sudo npm update"

# local remove
alias snpmr="sudo npm remove"
alias snpmx="snpmr"

## super user global
#######################################

# global install
alias npmig="npm install --global"
alias npmgi="npmig"
alias npmg="npmig"
alias snpmig="sudo npm install --global"
alias snpmgi="snpmig"
alias snpmg="snpmig"

# global update
alias npmupg="npm update --global"
alias npmgup="npmupg"
alias snpmupg="sudo npm update --global"
alias snpmgup="snpmupg"

# global remove
alias npmrg="npm remove --global"
alias npmgr="npmrg"
alias npmxg="npmrg"
alias npmgx="npmrg"
alias snpmrg="sudo npm remove --global"
alias snpmgr="snpmrg"
alias snpmxg="snpmrg"
alias snpmgx="snpmrg"

# Run NPM Install on all subdirectories
function subnpmi() {
  for d in $(find . -name 'package.json' | grep -v 'node_modules' | sed 's/\/package\.json//g'); do
    hr
    (
      cd "$d"
      echo "NPM Installing $d";
      npm install
    )
  done
}

# Reinstall modules completely
## local, no save
function npmri() {
  npmrs "$@"
  npmi "$@"
}
## local, save
function npmris() {
  npmrs "$@"
  npmris "$@"
}
## local, save exact
function npmrise() {
  npmrs "$@"
  npmise "$@"
}
## local, save dev
function npmrisd() {
  npmrsd "$@"
  npmisd "$@"
}
## local, save dev exact
function npmrisde() {
  npmrsd "$@"
  npmisde "$@"
}

# npm stars
function npmstars() {
  for p in $(npm stars $@); do
    npm view "$p" name description repository.url
    # echo "$p"
    hr
  done
}

# Check deps on subdirectories
function npm-check-subs() {
  for d in $(find . -name 'package.json' -maxdepth 2 | sed 's#/package.json##g'); do
    hr
    (
      cd "$d"
      echo "$d"
      npm install --silent
      npm-check -ps
    )
  done
}

# Check deps on subdirectiories AND clean up after
function npm-check-subs-clean() {
  local report_file=$(date +"%Y.%m.%d-%H%M%S")_deps_report.txt
  rm *_deps_report.txt 2>/dev/null

  for d in $(find . -name 'package.json' -maxdepth 2 | sed 's#/package.json##g'); do
    hr
    (
      cd "$d"
      echo "$d"
      npm install --silent >/dev/null
      hr >> "../$report_file"
      echo "$d" >> "../$report_file"
      npm-check -ps | lbl -e 'x=>!x.match(/^Use npm-check/) && log(x)' | tee -a "../$report_file"
    )
  done
  gtcleans >/dev/null
  echo "Results saved to: $report_file"
}
