#!/usr/bin/env bash

# Process Search by Name
alias psa="ps aux | grep -v 'grep' | grep "

# Process Kill Matching Name
function psakill() {
  ps aux | grep -v 'grep' | grep "$@" | awk '{print $2}' | xargs kill -9
}

# Process ID Search by Port
function psport() {
  if [[ $# -eq 0 ]]; then
    printf "\n  Usage: psport <port>\n\n"
  else
    pids="$(lsof -ti:$1)"
    if [[ "${#pids}" -eq 0  ]]; then
      echo "No process found for port: $1"
    else
      for pid in $pids
      do
        echo $pid
      done
    fi
  fi
}

# Process Search by Port
function psaport() {
  if [[ $# -eq 0 ]]; then
    printf "\n  Usage: psaport <port>\n\n"
  else
    psport "$@" | xargs -I{} ps -p {}
  fi
}

# Process Kill by Port
function killport() {
  if [[ $# -eq 0 ]]; then
    printf "\n  Usage: killport <port>\n\n"
  else
    lsof -ti:$1 | xargs -I{} kill -9 {}
  fi
}
