#!/usr/bin/env bash

# Process Search by Name
alias process_grep_name="ps aux | grep -v 'grep' | grep "

# Process Kill Matching Name
function process_kill_name() {
  ps aux | grep -v 'grep' | grep "$@" | awk '{print $2}' | xargs kill -9
}

# Process ID Search by Port
function process_id_for_port() {
  if [[ $# -eq 0 ]]; then
    printf "\n  Usage: process_id_for_port <port>\n\n"
  else
    pids="$(lsof -ti:$1)"
    if [[ "${#pids}" -eq 0  ]]; then
      echo "No process found for port: $1"
    else
      for pid in $pids
      do
        echo $pid
      done
    fi
  fi
}

# Process Search by Port
function process_details_for_port() {
  if [[ $# -eq 0 ]]; then
    printf "\n  Usage: process_details_for_port <port>\n\n"
  else
    process_id_for_port "$@" | xargs -I{} ps -p {}
  fi
}

# Process Kill by Port
function process_kill_for_port() {
  if [[ $# -eq 0 ]]; then
    printf "\n  Usage: process_kill_for_port <port>\n\n"
  else
    lsof -ti:$1 | xargs -I{} kill -9 {}
  fi
}
