#!/usr/bin/env bash

# Node version aliases
alias nvsh-neon="PROMPT_PREFIX=\"n16: \" nve 16 $SHELL"

fvm_dir="$HOME/fvm/default/bin"
if [[ "${PATH}" != *"${fvm_dir}"* ]]; then
  export PATH="$PATH:$fvm_dir"
fi

alias rosetta_simulator="open /Applications/Xcode.app/Contents/Developer/Applications/"

command -v flutter &>/dev/null && source <(flutter bash-completion)

function madprops_build_ios() {
  flutter clean &&
  flutter pub get &&
  flutter build ios --release ./lib/app_production.dart &&
  open ../ios/Runner.xcworkspace
}

function madprops_build_android() {
  flutter clean &&
  flutter pub get &&
  flutter build appbundle ./lib/app_production.dart &&
  open ../build/app/outputs/bundle/release/
}

function madprops_build_both() {
  flutter clean &&
  flutter pub get &&
  flutter build ios --release ./lib/app_production.dart &&
  open ../ios/Runner.xcworkspace &&
  flutter build appbundle ./lib/app_production.dart &&
  open ../build/app/outputs/bundle/release/
}

# Ngrok.com tunneling :: config file is as ~/.ngrok2/ngrok.yml
alias ngrok-neon-api='ngrok start neon-api'
alias ngrok-neon-ds='ngrok start neon-ds'
function neon-ngrok() {
  printf 'neon-api\nneon-ds' | ipt -a -M "Select an Ngrok Tunnel to Start:" | xargs -I{} ngrok start {}
}
