#!/bin/bash

# XDG Defaults
export XDG_CACHE_HOME="${HOME}/.cache"
mkdir -p "$XDG_CACHE_HOME"
export XDG_CONFIG_HOME="${HOME}/.config"
mkdir -p "$XDG_CONFIG_HOME"
export XDG_DATA_HOME="${HOME}/.local/share"
mkdir -p "$XDG_DATA_HOME"
