#!/usr/bin/env bash

[[ -f "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

if [[ -f "$HOME/.profiles/x/_profile" ]]; then
  source "$HOME/.profiles/x/_profile"
fi

if [[ -f "$HOME/.profiles/active/profile" ]]; then
  source "$HOME/.profiles/active/profile"
fi

if [[ -f "$HOME/.env" ]]; then
	export $(xargs < "$HOME/.env")
fi
