#!/usr/bin/env bash

# Application directories
export APPLICATIONS_DIR="/Applications"
export USER_APPLICATIONS_DIR="$HOME/Applications"
alias aapps="find $APPLICATIONS_DIR -regex '.*.app' | sed s#$APPLICATIONS_DIR/## | less -P '^ Apps in $APPLICATIONS_DIR'"
alias uapps="find $USER_APPLICATIONS_DIR -regex '.*.app' | sed s#$USER_APPLICATIONS_DIR/## | less -P '^ Apps in $USER_APPLICATIONS_DIR'"
alias apps="aapps && uapps"

# Show/hide HIDDEN files in Finder/Desktop
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Show/hide ALL files in Finder/Desktop
alias veil="defaults write com.apple.finder CreateDesktop false && killall Finder"
alias unveil="defaults write com.apple.finder CreateDesktop true && killall Finder"

# Open finder to system Fonts
alias fonts="open /Library/Fonts"
