#!/usr/bin/env bash

# Terminal Colors
export CLICOLOR="cxfxcxdxbxegedabagacad"
export LSCOLORS="cxfxcxdxbxegedabagacad"

# Clear terminal screen and remove backscroll
alias cl="clear && printf '\e[3J'"

# Cursor as editor, when possible
export EDITOR="cursor --classic"

# TextEdit (when desperate)
alias textedit='open -a TextEdit'

# Chrome browser from CLI
alias chrome="open -a $APPLICATIONS_DIR/Google\ Chrome.app"

# Surfraw
export SURFRAW_text_browser=lynx

